### ISSUE TITLE
why there are two subscription names, also why we getting subscription id first and then crate new ?

### ISSUE THREAD

**Issue by mztariq** [openrba/terraform-azurerm-subscription#1]
https://github.com/openrba/terraform-azurerm-subscription/blob/af1c113b8dae4a0f971bfa6f581a3b465683443c/main.tf#L20

**Comment by burgerjx** [comment]
The key subscription_name is passed in the query block to the external provider to create the subscription.  This should be set to the var.subscription name being passed into the module.
